stages:
  - setup
  - visual-regression
  - report

variables:
  NODE_VERSION: "18"
  WEBSITE_URL: "http://your-website-url.com" # Replace with your website URL

# Cache node_modules for faster builds
cache:
  paths:
    - node_modules/

setup:
  stage: setup
  image: node:$NODE_VERSION
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

# Set baseline (run manually when needed)
set_baseline:
  stage: visual-regression
  image: node:$NODE_VERSION
  script:
    - npm install
    - node index.js baseline
  artifacts:
    paths:
      - baseline/
    expire_in: 1 week
  when: manual
  only:
    - main

# Run visual regression tests
visual_regression_test:
  stage: visual-regression
  image: node:$NODE_VERSION
  script:
    - npm install
    - node index.js test --html
  artifacts:
    paths:
      - results/
    expire_in: 1 week
    reports:
      junit: results/junit-report.xml
  coverage: '/Success Rate: (\d+\.\d+)%/'
  # Run on all branches except main (unless manually triggered)
  except:
    - main
  # Allow failure for development branches
  allow_failure: true

# Run on main branch with stricter settings
visual_regression_main:
  stage: visual-regression
  image: node:$NODE_VERSION
  script:
    - npm install
    - node index.js test --html
  artifacts:
    paths:
      - results/
    expire_in: 1 month
    reports:
      junit: results/junit-report.xml
  coverage: '/Success Rate: (\d+\.\d+)%/'
  only:
    - main
  # Don't allow failure on main branch
  allow_failure: false

# Generate and publish reports
publish_report:
  stage: report
  image: alpine:latest
  script:
    - echo "Visual regression test results available in artifacts"
    - echo "Download the HTML report from the artifacts section"
  dependencies:
    - visual_regression_test
    - visual_regression_main
  only:
    - main
    - merge_requests

# Optional: Send notifications on failure
notify_failure:
  stage: report
  image: alpine:latest
  script:
    - echo "Visual regression tests failed!"
    - echo "Check the artifacts for detailed reports"
  when: on_failure
  only:
    - main
